### ISSUE TITLE
Crash on Singleplayer

### ISSUE THREAD

**Issue by zachsai** [Coda1552/Breezy#10]
https://gist.github.com/celsiusqc/2aa415a1768764b6abcc358decb2727f

![image](https://user-images.githubusercontent.com/63996164/215973415-c43487d3-12da-4023-9919-a04c6452028f.png)
![image](https://user-images.githubusercontent.com/63996164/215973442-3c0adea2-f9ce-4ce7-bf4b-6f6904d626e8.png)

**Comment by someaddons** [comment]
https://github.com/Coda1552/Breezy/blob/d82f7821a5728b407b7ba80447dbee5b3e541c0b/src/main/java/coda/breezy/Breezy.java#L81

The event is getting fired for both client and server world ticks, should check if its a client world

**Comment by Coda1552** [comment]
Should be fixed for the next version. If you still experience the crash, feel free to reopen this issue.
