### ISSUE TITLE
[Feature Request] blowing wind visual effect as a standalone mod

### ISSUE THREAD

**Issue by kuba26038** [Coda1552/Breezy#15]
The breezy mod is, for me, one of the more interesting mods maintained for the latest minecraft version, not because of it's mechanics, but because of the visual effects it adds. I don't know if the effects added by this mod interact with the wind system or not, but i was hoping that the two could be separated into different mods because of the miniscular, yet existing impact the wind mechanics have on my modpack's performance. And since i have no use for said system in my modpack, i really do think that making such a mod would be beneficial.

**Comment by Coda1552** [comment]
I'm a bit confused. You want the balloon and wind particles in a separate mod so that performance is boosted? I could just make the wind a config option like it was in 1.18.2 lol.

**Comment by kuba26038** [comment]
no, i want the visual effect as a standalone mod, without the wind mechanic and the balloons

**Comment by Coda1552** [comment]
Late reply, but the wind 'mechanics' have almost no performance difference, and if you don't want the balloons you can just remove their recipe with craft tweaker or something.
