### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by WenXin20** [Coda1552/Breezy#2]
```
Breezy v1.0.0
Forge v43.1.47
Minecraft v1.19.2
```
When installed on a server, it crashes :)
[Crash Report](https://gist.github.com/WenXin20/7db6145cf37cc0a0b7b5278185de3092)

**Comment by Straynv** [comment]
I have the same problem.

**Comment by Coda1552** [comment]
I believe its an issue with Breezy being made for an older version of Forge (43.1.0 to be exact). Try downgrading to that for now, I'm working on a fix.

**Comment by Coda1552** [comment]
Fixed.

**Comment by WenXin20** [comment]
Thanks!
