### ISSUE TITLE
Crash 1.19.2 --- has to do with wind direction reset every 24000 ticks

### ISSUE THREAD

**Issue by zachsai** [Coda1552/Breezy#20]
https://gist.github.com/celsiusqc/9db17c274777ec22be340950a368ddd0

![image](https://github.com/Coda1552/Breezy/assets/63996164/cfce2632-6e87-4ac1-8c4f-4f816d08bd61)

On latest 1.19.2 version

**Comment by HollyBlocky** [comment]
This happens to me, too

**Comment by koenigstag** [comment]
@Coda1552 issue fixed in https://github.com/Coda1552/Breezy/pull/22
