### ISSUE TITLE
World crashes as soon as you sleep in a new modpack 1.19.2

### ISSUE THREAD

**Issue by Aerhtjiz** [Coda1552/Breezy#23]
When you sleep in any type of bed in the game you almost immediately crashes

coda.breezy.Breezy.resetWindDirection(Breezy.java:67)

https://www.dropbox.com/scl/fi/cp87yxdxwfbhfsxy3a9ve/crash-2023-07-18_23.08.00-client.txt?rlkey=oy4zumkeojj79384sg3091fgl&dl=0

**Comment by thelegitdolt** [comment]
Can reproduce! Was just minecrafting around when the game suddenly crashed. Report: https://gist.github.com/thelegitdolt/063db9b452e6cb3305357a91bed629f4

**Comment by Coda1552** [comment]
Should be fixed.
