### ISSUE TITLE
Struggles to get altitude on multiplayer server

### ISSUE THREAD

**Issue by ArkVeil** [Coda1552/Breezy#3]
I've noticed on multiplayer servers, on take off the balloon gets extremely jittery and it becomes difficult to get any altitude for a while. Once you're up in the air for a while, the shakes stop and it becomes easier to control (as long as you also have a mod to fix "moved too quickly"). Did not occur when testing in a singleplayer world.

**Comment by Coda1552** [comment]
What version?

**Comment by ArkVeil** [comment]
Minecraft 1.19.2
Breezy 1.0.1

**Comment by Coda1552** [comment]
Can you get a video of this? I haven't noticed this on servers.

**Comment by ArkVeil** [comment]
I've since updated to Breezy 1.0.2, but this is the same behavior as before.

https://imgur.com/a/Jl8B45t
https://imgur.com/a/JVnbIfC

Mod list for the pack. I already tried removing canary but it didn't make a difference. 
[modlist.txt](https://github.com/Coda1552/Breezy/files/9896688/modlist.txt)

**Comment by Coda1552** [comment]
Hm. That is odd. Have you tried with just Breezy and GeckoLib installed? If not, can you please try that and see if you have the same issue?

**Comment by ArkVeil** [comment]
It's worth a shot. It will take a bit to take the server down and change the mods and world over so I'll let you know in a few days the results.

**Comment by ArkVeil** [comment]
https://imgur.com/a/DZ2ZRJM
The issue still occurs in an isolated environment.

Version Information:
Minecraft 1.19.2
Forge 43.1.47
GeckoLib 3.1.31
Breezy 1.0.2

**Comment by Coda1552** [comment]
Okay, thanks for confirming. I'll look into this.

**Comment by Hextaku** [comment]
I have the same issue. I also tested with render distance way down, both on client and server to reduce load, but the result is still the same.

**Comment by ArkVeil** [comment]
I don't think its a load issue. My guess is the server is struggling to properly track the position of the player, and thinks the player is several blocks lower than it really is and is not in a balloon.

**Comment by zachsai** [comment]
> I've since updated to Breezy 1.0.2, but this is the same behavior as before.
> 
> https://imgur.com/a/Jl8B45t https://imgur.com/a/JVnbIfC
> 
> Mod list for the pack. I already tried removing canary but it didn't make a difference. [modlist.txt](https://github.com/Coda1552/Breezy/files/9896688/modlist.txt)

off topic, what is the mod you are using to display coordinates on the top right with the time on the right?

**Comment by Coda1552** [comment]
Sorry for such a long wait... should be fixed now. If it's not, feel free to re open this issue.
