### ISSUE TITLE
[1.19.2 Forge 43.3.2] Baloon doesn't recognise modded firestarters.

### ISSUE THREAD

**Issue by Quartofel** [Coda1552/Breezy#32]
Hello! Would it be possible to add config options for "heat sources" or something similar? Right now, I'm using Simply Steel which adds separate Flint and Steel and Flint and Iron, and Flint and Iron cannot be used to gain altitude.

Thank you for your time, effort and the mod!

**Comment by Coda1552** [comment]
This already exists, tags/items/ignition_sources.json. You can modify it with a datapack.

**Comment by Quartofel** [comment]
My bad, sorry!

And thank you very much!

**Comment by Coda1552** [comment]
No worries. It’s not documented anywhere, so there’s no way you could have known. Let me know if it isn’t what you’re looking for.
