### ISSUE TITLE
[Suggestion] Could you make the flint and steel check be an itemtag check instead?

### ISSUE THREAD

**Issue by SeriousCreeper** [Coda1552/Breezy#5]
Heya,

i'm using breezy in my 1.18.2 TerraFirmaCraft modpack. TFC makes flint and steel really expensive (it's suppose to be a more late game item) and was wondering if you could make it use an itemtag instead, like how it does with the sand blocks? Then i could add some other firestarter items to the list :D 

Cheers,
SC

**Comment by Coda1552** [comment]
I can do that. Do you know what tag the fire starters are?

**Comment by SeriousCreeper** [comment]
Thanks!

I don't think there is a default one (at least flint and steel doesn't have one), so it would probably have to be a custom one added by breezy, and then other people/packdevs can add their items to that tag (as well as add the flint and steel to it by default).

**Comment by Coda1552** [comment]
Done. Sorry this took me so long to get to.
